/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlatformsRouteImport } from './routes/_authenticated/platforms'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicCronProcessJobsRouteImport } from './routes/api/public/cron/process-jobs'
import { Route as ApiPublicFeedsUserIdPfDotxmlRouteImport } from './routes/api/public/feeds/$userId/pf[.]xml'
import { Route as ApiPublicFeedsUserIdBayutDotxmlRouteImport } from './routes/api/public/feeds/$userId/bayut[.]xml'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformsRoute = AuthenticatedPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicCronProcessJobsRoute =
  ApiPublicCronProcessJobsRouteImport.update({
    id: '/api/public/cron/process-jobs',
    path: '/api/public/cron/process-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsUserIdPfDotxmlRoute =
  ApiPublicFeedsUserIdPfDotxmlRouteImport.update({
    id: '/api/public/feeds/$userId/pf.xml',
    path: '/api/public/feeds/$userId/pf.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsUserIdBayutDotxmlRoute =
  ApiPublicFeedsUserIdBayutDotxmlRouteImport.update({
    id: '/api/public/feeds/$userId/bayut.xml',
    path: '/api/public/feeds/$userId/bayut.xml',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/api/public/cron/process-jobs': typeof ApiPublicCronProcessJobsRoute
  '/api/public/feeds/$userId/bayut.xml': typeof ApiPublicFeedsUserIdBayutDotxmlRoute
  '/api/public/feeds/$userId/pf.xml': typeof ApiPublicFeedsUserIdPfDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/platforms': typeof AuthenticatedPlatformsRoute
  '/api/public/cron/process-jobs': typeof ApiPublicCronProcessJobsRoute
  '/api/public/feeds/$userId/bayut.xml': typeof ApiPublicFeedsUserIdBayutDotxmlRoute
  '/api/public/feeds/$userId/pf.xml': typeof ApiPublicFeedsUserIdPfDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/platforms': typeof AuthenticatedPlatformsRoute
  '/api/public/cron/process-jobs': typeof ApiPublicCronProcessJobsRoute
  '/api/public/feeds/$userId/bayut.xml': typeof ApiPublicFeedsUserIdBayutDotxmlRoute
  '/api/public/feeds/$userId/pf.xml': typeof ApiPublicFeedsUserIdPfDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/activity'
    | '/admin'
    | '/dashboard'
    | '/jobs'
    | '/listings'
    | '/platforms'
    | '/api/public/cron/process-jobs'
    | '/api/public/feeds/$userId/bayut.xml'
    | '/api/public/feeds/$userId/pf.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/activity'
    | '/admin'
    | '/dashboard'
    | '/jobs'
    | '/listings'
    | '/platforms'
    | '/api/public/cron/process-jobs'
    | '/api/public/feeds/$userId/bayut.xml'
    | '/api/public/feeds/$userId/pf.xml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs'
    | '/_authenticated/listings'
    | '/_authenticated/platforms'
    | '/api/public/cron/process-jobs'
    | '/api/public/feeds/$userId/bayut.xml'
    | '/api/public/feeds/$userId/pf.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCronProcessJobsRoute: typeof ApiPublicCronProcessJobsRoute
  ApiPublicFeedsUserIdBayutDotxmlRoute: typeof ApiPublicFeedsUserIdBayutDotxmlRoute
  ApiPublicFeedsUserIdPfDotxmlRoute: typeof ApiPublicFeedsUserIdPfDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platforms': {
      id: '/_authenticated/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedPlatformsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron/process-jobs': {
      id: '/api/public/cron/process-jobs'
      path: '/api/public/cron/process-jobs'
      fullPath: '/api/public/cron/process-jobs'
      preLoaderRoute: typeof ApiPublicCronProcessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/$userId/pf.xml': {
      id: '/api/public/feeds/$userId/pf.xml'
      path: '/api/public/feeds/$userId/pf.xml'
      fullPath: '/api/public/feeds/$userId/pf.xml'
      preLoaderRoute: typeof ApiPublicFeedsUserIdPfDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/$userId/bayut.xml': {
      id: '/api/public/feeds/$userId/bayut.xml'
      path: '/api/public/feeds/$userId/bayut.xml'
      fullPath: '/api/public/feeds/$userId/bayut.xml'
      preLoaderRoute: typeof ApiPublicFeedsUserIdBayutDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedPlatformsRoute: typeof AuthenticatedPlatformsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedPlatformsRoute: AuthenticatedPlatformsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCronProcessJobsRoute: ApiPublicCronProcessJobsRoute,
  ApiPublicFeedsUserIdBayutDotxmlRoute: ApiPublicFeedsUserIdBayutDotxmlRoute,
  ApiPublicFeedsUserIdPfDotxmlRoute: ApiPublicFeedsUserIdPfDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
